package parser

type wxBookDetail struct {
	ID                 int         `json:"Id"`
	ColumnID           int         `json:"ColumnId"`
	Code               string      `json:"Code"`
	Name               string      `json:"Name"`
	Author             string      `json:"Author"`
	Tags               string      `json:"Tags"`
	HomeImg            string      `json:"HomeImg"`
	PlayImg            string      `json:"PlayImg"`
	Abstract           string      `json:"Abstract"`
	IsRecommend        int         `json:"IsRecommend"`
	SetRecommendDate   string      `json:"SetRecommendDate"`
	IsHot              int         `json:"IsHot"`
	SetHotDate         string      `json:"SetHotDate"`
	IsSelected         int         `json:"IsSelected"`
	SetSelectedDate    string      `json:"SetSelectedDate"`
	IsSlide            int         `json:"IsSlide"`
	SetSlideDate       string      `json:"SetSlideDate"`
	IsPay              int         `json:"IsPay"`
	PayPrice           float64     `json:"PayPrice"`
	Point              int         `json:"Point"`
	IsComment          int         `json:"IsComment"`
	IsActivity         int         `json:"IsActivity"`
	ClickTimes         int         `json:"ClickTimes"`
	SeoTitle           interface{} `json:"SeoTitle"`
	SeoKeywords        interface{} `json:"SeoKeywords"`
	SeoDescriptions    interface{} `json:"SeoDescriptions"`
	AudioSort          int         `json:"AudioSort"`
	Title              string      `json:"Title"`
	AudioAbstract      string      `json:"AudioAbstract"`
	FileName           string      `json:"FileName"`
	APlayImg           string      `json:"APlayImg"`
	FilePath           string      `json:"FilePath"`
	FileSuffix         string      `json:"FileSuffix"`
	FileSize           int         `json:"FileSize"`
	FileDuration       int         `json:"FileDuration"`
	ListenFileName     interface{} `json:"ListenFileName"`
	ListenFilePath     interface{} `json:"ListenFilePath"`
	ListenFileSize     int         `json:"ListenFileSize"`
	ListenFileSuffix   interface{} `json:"ListenFileSuffix"`
	ListenFileDuration int         `json:"ListenFileDuration"`
	PlayTimes          int         `json:"PlayTimes"`
	AuditStatus        int         `json:"AuditStatus"`
	AuditUserID        int         `json:"AuditUserId"`
	AuditUserRealname  interface{} `json:"AuditUserRealname"`
	AuditDate          interface{} `json:"AuditDate"`
	AuditDesc          interface{} `json:"AuditDesc"`
	AuditLog           interface{} `json:"AuditLog"`
	IsEnabled          int         `json:"IsEnabled"`
	IsDelete           int         `json:"IsDelete"`
	SortCode           int         `json:"SortCode"`
	Remark             interface{} `json:"Remark"`
	CreateDate         string      `json:"CreateDate"`
	AID                int         `json:"AId"`
	AAbstract          string      `json:"AAbstract"`
}

type wxBookList struct {
	ID                 int         `json:"Id"`
	ColumnID           int         `json:"ColumnId"`
	Code               string      `json:"Code"`
	Name               string      `json:"Name"`
	Author             string      `json:"Author"`
	Tags               string      `json:"Tags"`
	HomeImg            string      `json:"HomeImg"`
	PlayImg            string      `json:"PlayImg"`
	Abstract           string      `json:"Abstract"`
	IsRecommend        int         `json:"IsRecommend"`
	SetRecommendDate   interface{} `json:"SetRecommendDate"`
	IsHot              int         `json:"IsHot"`
	SetHotDate         interface{} `json:"SetHotDate"`
	IsSelected         int         `json:"IsSelected"`
	SetSelectedDate    interface{} `json:"SetSelectedDate"`
	IsSlide            int         `json:"IsSlide"`
	SetSlideDate       interface{} `json:"SetSlideDate"`
	IsPay              int         `json:"IsPay"`
	PayPrice           float64     `json:"PayPrice"`
	Point              int         `json:"Point"`
	IsComment          int         `json:"IsComment"`
	IsActivity         int         `json:"IsActivity"`
	ClickTimes         int         `json:"ClickTimes"`
	SeoTitle           string      `json:"SeoTitle"`
	SeoKeywords        string      `json:"SeoKeywords"`
	SeoDescriptions    string      `json:"SeoDescriptions"`
	IsEnabled          int         `json:"IsEnabled"`
	IsDelete           int         `json:"IsDelete"`
	AudioSort          int         `json:"AudioSort"`
	SortCode           int         `json:"SortCode"`
	ColumnSortCode     int         `json:"ColumnSortCode"`
	Remark             interface{} `json:"Remark"`
	CreateDate         string      `json:"CreateDate"`
	CreateUserID       string      `json:"CreateUserId"`
	CreateUserRealname string      `json:"CreateUserRealname"`
	ModifyDate         string      `json:"ModifyDate"`
	ModifyUserID       string      `json:"ModifyUserId"`
	ModifyUserRealname string      `json:"ModifyUserRealname"`
	BookID             int         `json:"BookId"`
	PlayTimes          int         `json:"PlayTimes"`
}
